package Assignments.Assignment1;
// ------------------------------------------------------- 
// Assignment 1 - Question #2
// Written by: Catalin-Ion Besleaga (40347936)
// For COMP 248 Section S – Fall 2025
// --------------------------------------------------------

import java.util.Scanner;

/*
 * This program prompts the user to enter their favorite color, animal, and their city of birth. It will then generate a
 * "Screen name" and "Secret code" which it will display to the user to utilize.
 */

public class Assignment1Q2 {

	public static void main(String[] args) {
        Scanner keyReader = new Scanner(System.in);
		System.out.println("Welcome! Let's generate your screen name and secret code.");
		System.out.println();
		/*
		 * The program will prompt the user to enter their favorite color, animal, and birth city.
		 */
		System.out.print("Enter your favorite color: ");
		String color = keyReader.next();
		
		System.out.print("Enter your favorite animal: ");
		String animal = keyReader.next();
		
		System.out.print("Enter the city where you were born: ");
		String city = keyReader.next();
		
		System.out.println("");
		
		/*
		 * The program will generate a screen name and secret code based on the user's inputs.
		 * Screen Name Generation:
		 * - The screen name is created by concatenating the last three characters of the favorite color,
		 *   the first three characters of the favorite animal, and the length of the birth city
		 */
		int lastThreeCharColor = color.length() - 3;
		String colorSub = color.substring(lastThreeCharColor);
		String animalSub = animal.substring(0, 3);
		int cityLength = city.length();
		String secretName = colorSub + animalSub + cityLength;
		
		System.out.println("Generated Screen Name: " + secretName);


		/*
		 * Secret Code Generation:
		 * - The secret code is generated by concatenating the first character of the favorite color,
		 *   the last character of the favorite animal (converted to uppercase), and the substring of the birth city
		 *   excluding its first and last characters.
		 * - The third character of the secret code is replaced with an asterisk (*).
		 * - A random digit between 1 and 9 is appended to the end of the secret code.
		 */

		String concInputs = color + animal + city;
		char firstChar = concInputs.charAt(0);
		char lastChar = concInputs.charAt(concInputs.length() - 1);
		String concInputsSub = concInputs.substring(1, concInputs.length() - 1);
		/*
		 * EXPLANATION:
		 * - The first character of the concatenated string is obtained using charAt(0).
		 * - The last character is obtained using charAt(length - 1) since the index is zero-based.
		 * - The substring excluding the first and last characters is obtained using substring(1, length - 1).
		 */
		
		String lC = lastChar + "o";
		String upperlC = lC.toUpperCase();
		char truLastChar = upperlC.charAt(0);
		/*
		 * EXPLANATION:
		 * - The last character is concatenated with a dummy character "o" to form a string.
		 * - The toUpperCase() method is used to convert the entire string to uppercase.
		 * - The first character of the uppercase string is extracted using charAt(0), which gives the uppercase version
		 *	 of the original last character.
		 */
		
		String swapped = truLastChar + concInputsSub + firstChar;
		String secretCodeSub1 = swapped.substring(0, 2);
		String secretCodeSub2 = swapped.substring(3);
		int randomInt = (int)(Math.random() * 9) + 1;
		/*
		 * EXPLANATION:
		 * - The secret code is formed by concatenating the uppercase last character, the substring excluding
		 *   the first and last characters, and the first character.
		 * - The substring method is used to extract the parts of the secret code before and after the third character.
		 * - A random integer between 1 and 9 is generated using Math.random(), which is then scaled and shifted to the desired range.
		 */
		
		System.out.println("Generated secret code: " + secretCodeSub1 + "*" + secretCodeSub2 + randomInt);
		System.out.println();
		System.out.println("Thank you for using my program. Goodbye!");
		keyReader.close();
		/*
		 * The generated screen name and secret code are displayed to the user.
		 * The program thanks the user for using it and then terminates.
		 * The Scanner object is closed to prevent resource leaks.
		 */
	}
}
